### ISSUE TITLE
How to test element states

### ISSUE THREAD

**Issue by AlbertLucianto** [fwouts/react-screenshot-test#180]
Hi, thanks for this amazing library, it's super easy to setup and works great. :raised_hands:

I'm just wondering if there's any way to screenshot element states like `:hover` or `:focus`. Also, is it possible to interact with the component before screenshot is taken?

**Comment by fwouts** [comment]
> Hi, thanks for this amazing library, it's super easy to setup and works great. 🙌

Really glad to hear, thanks Albert!

> I'm just wondering if there's any way to screenshot element states like `:hover` or `:focus`.

That's a good question.

It's not currently possible, but it should be possible to implement:
- [Puppeteer does have hover() and focus()](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md)
- It should also be possible with WebdriverIO, [although a bit less easily](https://blog.kevinlamping.com/set-keyboard-focus-on-an-element-via-webdriverio/)

To give you an idea of the work required, we'd need to:
- Update [each renderer](https://github.com/fwouts/react-screenshot-test/tree/master/src/lib/screenshot-renderer) to take in an argument in `render()` specifying a selector for hover or focus.
- Update [LocalScreenshotServer](https://github.com/fwouts/react-screenshot-test/blob/master/src/lib/screenshot-server/LocalScreenshotServer.ts) to accept new fields in the request body specifying a selector.
- Release a new version of the Docker image [fwouts/chrome-screenshot](https://github.com/fwouts/react-screenshot-test/blob/master/Dockerfile) with support for the new fields.
- Update [ReactScreenshotTest](https://github.com/fwouts/react-screenshot-test/blob/master/src/lib/react/ReactScreenshotTest.ts#L81) to accept optional selectors for each shot, and [pass them to render()](https://github.com/fwouts/react-screenshot-test/blob/master/src/lib/react/ReactScreenshotTest.ts#L157).

Would you be interested in giving it a try?

> Also, is it possible to interact with the component before screenshot is taken?

Components are rendered server-side without hydration (they're plain HTML, there is no JavaScript on the page), so they will not be interactable.

It might be possible to re-do how rendering works to support hydration, but unfortunately, that would require completely rethinking how the library works. It would also likely result in reduced performance because it would require an extra compilation step for each component.

Cheers!
