### ISSUE TITLE
Delay screenshot capture after page rendering 

### ISSUE THREAD

**Issue by YuriyBC** [fwouts/react-screenshot-test#225]
Sometimes react component requires js file or some api call and it cannot be immedeatly rendered. Right now screenshot captures without delay and react component can return empty node. So, it will allow to support non-pure components. 

class PuppeteerScreenshotRenderer calls `await page.goto`  with url. According [docs](https://pptr.dev/#?product=Puppeteer&version=v3.3.0&show=api-pagegotourl-options) object configuration can be provided `{ timeout: 500 }` for example. It will be helpful to provide this functionality.

**Comment by fwouts** [comment]
Hi @YuriyBC, thanks for filing this issue.

It may be worth clarifying that unlike a usual React application, react-screenshot-test exclusively uses server-side rendering. There is no client-side hydration, and as such callbacks such as `componentDidMount` will never be called, no matter how long you wait.

This is a technical limitation because react-screenshot-test is not sophisticated enough to generate a client-side JS bundle. See [the docs](https://github.com/fwouts/react-screenshot-test/blob/master/docs/index.md) if you'd like to understand how it works under the hood.

This means that at this stage, react-screenshot-test is not the right solution if you want to screenshot test stateful components.
