### ISSUE TITLE
Waiting to render components asyncronously

### ISSUE THREAD

**Issue by nweajoseph** [fwouts/react-screenshot-test#303]
What would it take to implement waiting for asynchronous component results using the Jest async completion API? I guess it would look something like this:

```jsx
ReactScreenshotTest.create(/*...*/)
  .viewport("Desktop", { /*...*/ })
  .shoot(
    "app", 
     <DataProvider> // <---- this does async stuff, so <App/> isn't ready to shoot on the first render pass
        <App />
     </DataProvider>
  )
  .after(5000) // <---- i guess you would need to add some kind of API since you don't have direct access to the jest spec `done` callback
  .run();
```

I'm just not sure how else you would capture an image of any screen that had an external data dependency (most screens?). That would be too bad, since to me it seems like those are some of the highest value images to test. You could capture images of individual components like buttons and inputs, but a lot of those can be supplanted by a single "here's the whole thing together" picture.

**Comment by fwouts** [comment]
Hey @nweajoseph, thanks for filing this issue.

Unfortunately this is impossible with the current architecture of `react-screenshot-test`, because it **only** does server-side rendering. There is no client-side hydration, and in fact no JavaScript running in the browser at all. This is a limitation of the architecture, and not something that can be fixed easily. If your app supports server-side rendering, you can still make this work, but otherwise you're out of luck for now.

On the bright side, as part of building [an unrelated project](https://reactpreview.com) recently, I came up with a potential alternative architecture, and I'm planning to start building it next month. We can leave this issue open until I have a beta to share?

Full disclaimer: I'm not yet sure whether this new solution will also be free and open source or not, as I've just left my job to focus on these projects.

**Comment by rambabusaravanan** [comment]
Only capturing the first render may not sounds good in all the cases. If the below can be planned in future, this library would be a game changer.

**Second render / After mount**
We have lot of use cases that component render empty on first render and on load it computes in useEffect and then render the actual view on second render. We couldn't use the library in this case.

**Event firing**
If we can capture screenshot after firing event like change / click, that would be awesome. I hope this is needed for many basic test cases. e.g., 

**Time based waiting**
As @nweajoseph mentioned, if we can capture screenshot after a specified duration, that would be nice.
e.g., component view with a timer

**Comment by fwouts** [comment]
Hi folks, here's an update: react-screenshot-test v3 is coming soon with client-side support. This will be a backwards-incompatible change, with a simpler API and much faster screenshot generation. I'm hoping to get something out in the next month or so. Perhaps earlier.

**Comment by fwouts** [comment]
Hi @nweajoseph and @rambabusaravanan.

The new version of React Screenshot Test is out. It ended up becoming a very different library, with a new name too, since it's no longer specific to React.

You can give it a try at https://github.com/zenclabs/viteshot. See `beforeScreenshot` in https://github.com/zenclabs/viteshot/blob/main/examples/react/src/App.screenshot.tsx for an example of async waiting for an action to happen before taking a screenshot.

Let me know what you think! It's early days so we can tweak the API easily.
